# Generated by Django 4.2.23 on 2025-08-02 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comicvine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicVineIssue',
            fields=[
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('cache_expires', models.DateTimeField()),
                ('api_fetch_failed', models.BooleanField(default=False)),
                ('api_fetch_failure_count', models.IntegerField(default=0)),
                ('api_last_failure', models.DateTimeField(blank=True, null=True)),
                ('cv_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('cover_date', models.DateField(blank=True, null=True)),
                ('store_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('aliases', models.TextField(blank=True, null=True)),
                ('api_url', models.URLField(blank=True, null=True)),
                ('site_url', models.URLField(blank=True, null=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('date_last_updated', models.DateTimeField(blank=True, null=True)),
                ('image_icon_url', models.URLField(blank=True, null=True)),
                ('image_thumbnail_url', models.URLField(blank=True, null=True)),
                ('image_tiny_url', models.URLField(blank=True, null=True)),
                ('image_small_url', models.URLField(blank=True, null=True)),
                ('image_medium_url', models.URLField(blank=True, null=True)),
                ('image_screen_url', models.URLField(blank=True, null=True)),
                ('image_super_url', models.URLField(blank=True, null=True)),
                ('image_large_screen_url', models.URLField(blank=True, null=True)),
                ('image_original_url', models.URLField(blank=True, null=True)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='comicvine.comicvinevolume')),
            ],
            options={
                'verbose_name_plural': 'ComicVine Issues',
                'db_table': 'comicvine_issues',
                'ordering': ['volume', 'store_date', 'cover_date', 'number'],
                'indexes': [models.Index(fields=['volume', 'store_date'], name='comicvine_i_volume__9ece80_idx'), models.Index(fields=['volume', 'number'], name='comicvine_i_volume__e7ec4e_idx'), models.Index(fields=['store_date'], name='comicvine_i_store_d_2b74cd_idx')],
            },
        ),
    ]
