# Generated by Django 4.2.23 on 2025-08-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicvine', '0002_comicvineissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicvinevolume',
            name='count_of_issues',
            field=models.IntegerField(default=0),
        ),
    ]
