# Generated by GitHub Copilot
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comicvine", "0003_add_count_of_issues_to_volume"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComicVineCacheWeek",
            fields=[
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("cache_expires", models.DateTimeField()),
                ("api_fetch_failed", models.BooleanField(default=False)),
                ("api_fetch_failure_count", models.IntegerField(default=0)),
                ("api_last_failure", models.DateTimeField(blank=True, null=True)),
                ("week_start", models.DateField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "comicvine_weeks",
                "verbose_name": "ComicVine Weekly Cache",
                "verbose_name_plural": "ComicVine Weekly Caches",
            },
        ),
    ]
