# Generated by ChatGPT - add ComicVinePublisher and link from Volume
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("comicvine", "0004_comicvinecacheweek"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComicVinePublisher",
            fields=[
                (
                    "cv_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "comicvine_publishers",
                "verbose_name": "ComicVine Publisher",
                "verbose_name_plural": "ComicVine Publishers",
            },
        ),
        migrations.AddField(
            model_name="comicvinevolume",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.SET_NULL,
                blank=True,
                null=True,
                related_name="volumes",
                to="comicvine.comicvinepublisher",
            ),
        ),
    ]
