# Generated by Django 5.2.5 on 2025-08-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comicvine", "0008_add_issue_date_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comicvineissue",
            options={
                "ordering": ["volume", "date", "number"],
                "verbose_name_plural": "ComicVine Issues",
            },
        ),
        migrations.RemoveIndex(
            model_name="comicvineissue",
            name="comicvine_i_volume__9ece80_idx",
        ),
        migrations.RemoveIndex(
            model_name="comicvineissue",
            name="comicvine_i_store_d_2b74cd_idx",
        ),
        migrations.AddIndex(
            model_name="comicvineissue",
            index=models.Index(
                fields=["volume", "date"], name="comicvine_i_volume__46929f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comicvineissue",
            index=models.Index(fields=["date"], name="comicvine_i_date_dc558c_idx"),
        ),
    ]
