# Generated by Django 5.2.5 on 2025-08-24 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comicvine", "0009_alter_comicvineissue_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comicvineissue",
            name="cover_date",
        ),
        migrations.RemoveField(
            model_name="comicvineissue",
            name="store_date",
        ),
    ]
