# Generated by Django 5.2.6 on 2025-09-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comicvine", "0012_alter_comicvineweek_pk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comicvineweek",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
