# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-09 18:21
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.IntegerField()),
                ('read', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('skipped', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
    ]
