# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-11 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulls', '0005_series_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='series_id',
            field=models.IntegerField(unique=True),
        ),
    ]
