# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-24 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("pulls", "0006_auto_20171011_1336"),
    ]

    operations = [
        migrations.AddField(
            model_name="pull",
            name="idu",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="pull",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="pull",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="pull",
            name="series_id",
            field=models.IntegerField(),
        ),
    ]
