# Generated by Django 4.2.23 on 2025-08-03 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pulls", "0015_pull_migrated_to_comicvine"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pull",
            name="migrated_to_comicvine",
        ),
    ]
