# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-24 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=280)),
            ],
            options={
                'verbose_name_plural': 'lists',
            },
        ),
    ]
