# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-21 03:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pull_lists', '0003_pulllist_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulllist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
