# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-07 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pull_lists", "0004_auto_20180121_0337"),
    ]

    operations = [
        migrations.AddField(
            model_name="pulllist",
            name="mu_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
